name: Release Preview Nuget Package

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-pre[0-9][0-9][0-9]"

defaults:
  run:
    working-directory: ./Matomo.Maui

jobs:
  build:
    runs-on: windows-latest
    env:
      working-directory: ./Matomo.Maui
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify commit exists in origin/main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');

      #- name: Setup nuget
      #  uses: nuget/setup-nuget@v1
      - name: Restore nuget packages for solution
        run: dotnet restore Matomo.Maui.csproj

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3
      - name: Build
        run: msbuild Matomo.Maui.csproj /property:Configuration=Release
      - name: Pack
        run: |
          $version=${{ steps.tag.outputs.result }}
          $version=$version.replace("refs/tags/v", "")
          dotnet pack Matomo.Maui.csproj -p:NuspecFile=Matomo.Maui.nuspec -c Release -v detailed -p:NuspecBasePath=./ -o ./package -p:PackageVersion=$version
      - name: Push
        run: |
          $version=${{ steps.tag.outputs.result }}
          $version=$version.replace("refs/tags/v", "")
          $package="package/Matomo.Maui." + $version + ".nupkg"
          dotnet nuget push $package -s https://api.nuget.org/v3/index.json -k "$env:NUGET_ORG_TOKEN"
        env:
          NUGET_ORG_TOKEN: ${{ secrets.NUGET_ORG_TOKEN }}